version: "3"


services:
  db:
    restart: always
    image: postgres:9.5
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABAE_USERNAME}
      POSTGRES_DB: ${DATABAE_NAME}
  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redisdata:/redisdata
  app:
    restart: always
    container_name: hivery_coding_test_app
    build: ./app
    env_file: .env
    environment:
      REDIS_HOST: "redis"
    ports:
      - "9000:9000"
    volumes:
      - ./app:/app
    depends_on:
      - db
      - redis
    command: python3 manage.py runserver 0.0.0.0:9000
